<?php

class OpenCNAM extends superfecta_base {

    public $description = "https://www.opencnam.com has been deprecated.  Please use EveryoneAPI instead.";
    public $version_requirement = "2.11";
    public $source_param = array(
        'disabled' => array(
                'default' => 'OpenCNAM for Superfecta has been deprecated.  Please use EveryoneAPI instead.',
                'type' => 'textarea',
                'description' => 'This module is disabled.'
        ),
    );

    function get_caller_id($thenumber, $run_param=array()) {
        $caller_id = null;
        $this->DebugPrint("OpenCNAM is inactive.");
        return($caller_id);
    }

}
